version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: park-h-db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=garagem123467
      - POSTGRES_DB=parkh
      - POSTGRES_USER=postgres
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data

  app:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: park-h-app
    restart: always
    tty: true
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:5432/parkh
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=garagem123467
    ports:
      - "8080:8080"
