package app.prod.src.backend_pay_data.entity;

import java.math.BigDecimal;
import java.util.Objects;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "datapay")
public class FormasdePagamento {
	
	private String id;
	private String tipoPagamento;
	private BigDecimal preco;	
	
	public FormasdePagamento() {
		super();
		// TODO Auto-generated constructor stub
	}

	public FormasdePagamento(String tipoPagamento, BigDecimal preco) {
		super();
		this.tipoPagamento = tipoPagamento;
		this.preco = preco;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getTipoPagamento() {
		return tipoPagamento;
	}

	public void setTipoPagamento(String tipoPagamento) {
		this.tipoPagamento = tipoPagamento;
	}

	public BigDecimal getPreco() {
		return preco;
	}

	public void setPreco(BigDecimal preco) {
		this.preco = preco;
	}

	@Override
	public String toString() {
		return "FormasdePagamento [id=" + id + ", tipoPagamento=" + tipoPagamento + ", preco=" + preco + "]";
	}

	@Override
	public int hashCode() {
		return Objects.hash(id, preco, tipoPagamento);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		FormasdePagamento other = (FormasdePagamento) obj;
		return Objects.equals(id, other.id) && Objects.equals(preco, other.preco)
				&& Objects.equals(tipoPagamento, other.tipoPagamento);
	}
	
}
