package app.prod.src.backend_address.entity;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "addressgarage")
public class AddressGarage {

	private String id;
	private String title;
	private String nameState;
	private String cityname;
	private String streetname;
	private String districtname;
	private String addressnumber;
	private Date date;

	public AddressGarage() {
		super();
	}

	public AddressGarage(String title, String nameState, String cityname, String streetname, String districtname, String number, Date date) {
		
		super();
	    
		this.title = title;
		this.nameState = nameState;
		this.cityname = cityname;
		this.streetname = streetname;
		this.districtname = districtname;
		this.addressnumber = number;
		this.date = date;
	}

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}
    
	@DynamoDBAttribute
	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@DynamoDBAttribute
	public String getNameState() {
		return nameState;
	}

	public void setNameState(String nameState) {
		this.nameState = nameState;
	}

	@DynamoDBAttribute
	public String getCityname() {
		return cityname;
	}

	public void setCityname(String cityname) {
		this.cityname = cityname;
	}

	@DynamoDBAttribute
	public String getStreetname() {
		return streetname;
	}

	public void setStreetname(String streetname) {
		this.streetname = streetname;
	}

	@DynamoDBAttribute
	public String getDistrictname() {
		return districtname;
	}

	public void setDistrictname(String districtname) {
		this.districtname = districtname;
	}

	@DynamoDBAttribute
	public String getNumber() {
		return addressnumber;
	}

	public void setNumber(String number) {
		this.addressnumber = number;
	}
	
	public String getAddressnumber() {
		return addressnumber;
	}

	public void setAddressnumber(String addressnumber) {
		this.addressnumber = addressnumber;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Override
	public String toString() {
		return "AddressGarage [id: " + id + ", title: " + title + ", nameState: " + nameState + ", cityname: " + cityname
				+ ", streetname: " + streetname + ", districtname: " + districtname + ", addressnumber: " + addressnumber
				+ ", date: " + date + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((addressnumber == null) ? 0 : addressnumber.hashCode());
		result = prime * result + ((cityname == null) ? 0 : cityname.hashCode());
		result = prime * result + ((date == null) ? 0 : date.hashCode());
		result = prime * result + ((districtname == null) ? 0 : districtname.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((nameState == null) ? 0 : nameState.hashCode());
		result = prime * result + ((streetname == null) ? 0 : streetname.hashCode());
		result = prime * result + ((title == null) ? 0 : title.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		AddressGarage other = (AddressGarage) obj;
		if (addressnumber == null) {
			if (other.addressnumber != null)
				return false;
		} else if (!addressnumber.equals(other.addressnumber))
			return false;
		if (cityname == null) {
			if (other.cityname != null)
				return false;
		} else if (!cityname.equals(other.cityname))
			return false;
		if (date == null) {
			if (other.date != null)
				return false;
		} else if (!date.equals(other.date))
			return false;
		if (districtname == null) {
			if (other.districtname != null)
				return false;
		} else if (!districtname.equals(other.districtname))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (nameState == null) {
			if (other.nameState != null)
				return false;
		} else if (!nameState.equals(other.nameState))
			return false;
		if (streetname == null) {
			if (other.streetname != null)
				return false;
		} else if (!streetname.equals(other.streetname))
			return false;
		if (title == null) {
			if (other.title != null)
				return false;
		} else if (!title.equals(other.title))
			return false;
		return true;
	}

	
}
