package app.src.cod.entidade;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Objects;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "NOME DA TABELA CRIADA NA AWS")
public class AluguelGaragem {

	private String id;
	
	private String nomeResponsavel;
	private String codigoCadastro;
	private String emailResponsavel;
	private String contatoCelular;
	private String telefoneFixo;
	
	private String nomeBanco;
	private String codigoBanco;
	private String numeroAgencia;
	private String contaCorrente;
	private String chavePix;
	
	private String tituloAnuncio;
	private String tipoLogradouroString;
	private String tamanhoLocal;
	private String tipoVeiculo;
	private String capacidade;
	private String horarioFuncionamento;
	private String[] diasdaSemana;
	private String descricaoLocal;
	private String portaria;
	private String[] recursosVigilancia;

	private String cep;
	private String estado;
	private String cidade;
	private String rua;
	private String bairro;
	private String numero;
	private String complementoLocal;
    
	private String tipoPagamento;
	private BigDecimal preco;
	private String temIPTU;
    private String[] canaisPagamento;
	
	public AluguelGaragem() {
		super();
	}

	public AluguelGaragem(String id, String nomeResponsavel, String codigoCadastro, String emailResponsavel,
			String contatoCelular, String telefoneFixo, String nomeBanco, String codigoBanco, String numeroAgencia,
			String contaCorrente, String chavePix, String tituloAnuncio, String tipoLogradouroString,
			String tamanhoLocal, String tipoVeiculo, String capacidade, String horarioFuncionamento,
			String[] diasdaSemana, String descricaoLocal, String portaria, String[] recursosVigilancia, String cep,
			String estado, String cidade, String rua, String bairro, String numero, String complementoLocal,
			String tipoPagamento, BigDecimal preco, String temIPTU, String[] canaisPagamento) {
		super();
		
		this.id = id;
		this.nomeResponsavel = nomeResponsavel;
		this.codigoCadastro = codigoCadastro;
		this.emailResponsavel = emailResponsavel;
		this.contatoCelular = contatoCelular;
		this.telefoneFixo = telefoneFixo;
		this.nomeBanco = nomeBanco;
		this.codigoBanco = codigoBanco;
		this.numeroAgencia = numeroAgencia;
		this.contaCorrente = contaCorrente;
		this.chavePix = chavePix;
		this.tituloAnuncio = tituloAnuncio;
		this.tipoLogradouroString = tipoLogradouroString;
		this.tamanhoLocal = tamanhoLocal;
		this.tipoVeiculo = tipoVeiculo;
		this.capacidade = capacidade;
		this.horarioFuncionamento = horarioFuncionamento;
		this.diasdaSemana = diasdaSemana;
		this.descricaoLocal = descricaoLocal;
		this.portaria = portaria;
		this.recursosVigilancia = recursosVigilancia;
		this.cep = cep;
		this.estado = estado;
		this.cidade = cidade;
		this.rua = rua;
		this.bairro = bairro;
		this.numero = numero;
		this.complementoLocal = complementoLocal;
		this.tipoPagamento = tipoPagamento;
		this.preco = preco;
		this.temIPTU = temIPTU;
		this.canaisPagamento = canaisPagamento;
	}
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute
	public String getNomeResponsavel() {
		return nomeResponsavel;
	}

	public void setNomeResponsavel(String nomeResponsavel) {
		this.nomeResponsavel = nomeResponsavel;
	}

	@DynamoDBAttribute
	public String getCodigoCadastro() {
		return codigoCadastro;
	}

	public void setCodigoCadastro(String codigoCadastro) {
		this.codigoCadastro = codigoCadastro;
	}

	@DynamoDBAttribute
	public String getEmailResponsavel() {
		return emailResponsavel;
	}

	public void setEmailResponsavel(String emailResponsavel) {
		this.emailResponsavel = emailResponsavel;
	}

	@DynamoDBAttribute
	public String getContatoCelular() {
		return contatoCelular;
	}

	public void setContatoCelular(String contatoCelular) {
		this.contatoCelular = contatoCelular;
	}

	@DynamoDBAttribute
	public String getTelefoneFixo() {
		return telefoneFixo;
	}

	public void setTelefoneFixo(String telefoneFixo) {
		this.telefoneFixo = telefoneFixo;
	}

	@DynamoDBAttribute
	public String getNomeBanco() {
		return nomeBanco;
	}

	public void setNomeBanco(String nomeBanco) {
		this.nomeBanco = nomeBanco;
	}

	@DynamoDBAttribute
	public String getCodigoBanco() {
		return codigoBanco;
	}

	public void setCodigoBanco(String codigoBanco) {
		this.codigoBanco = codigoBanco;
	}

	@DynamoDBAttribute
	public String getNumeroAgencia() {
		return numeroAgencia;
	}

	public void setNumeroAgencia(String numeroAgencia) {
		this.numeroAgencia = numeroAgencia;
	}

	@DynamoDBAttribute
	public String getContaCorrente() {
		return contaCorrente;
	}

	public void setContaCorrente(String contaCorrente) {
		this.contaCorrente = contaCorrente;
	}

	@DynamoDBAttribute
	public String getChavePix() {
		return chavePix;
	}

	public void setChavePix(String chavePix) {
		this.chavePix = chavePix;
	}

	@DynamoDBAttribute
	public String getTituloAnuncio() {
		return tituloAnuncio;
	}

	public void setTituloAnuncio(String tituloAnuncio) {
		this.tituloAnuncio = tituloAnuncio;
	}

	@DynamoDBAttribute
	public String getTipoLogradouroString() {
		return tipoLogradouroString;
	}

	public void setTipoLogradouroString(String tipoLogradouroString) {
		this.tipoLogradouroString = tipoLogradouroString;
	}

	@DynamoDBAttribute
	public String getTamanhoLocal() {
		return tamanhoLocal;
	}

	public void setTamanhoLocal(String tamanhoLocal) {
		this.tamanhoLocal = tamanhoLocal;
	}

	@DynamoDBAttribute
	public String getTipoVeiculo() {
		return tipoVeiculo;
	}

	public void setTipoVeiculo(String tipoVeiculo) {
		this.tipoVeiculo = tipoVeiculo;
	}

	@DynamoDBAttribute
	public String getCapacidade() {
		return capacidade;
	}

	public void setCapacidade(String capacidade) {
		this.capacidade = capacidade;
	}

	@DynamoDBAttribute
	public String getHorarioFuncionamento() {
		return horarioFuncionamento;
	}

	public void setHorarioFuncionamento(String horarioFuncionamento) {
		this.horarioFuncionamento = horarioFuncionamento;
	}

	@DynamoDBAttribute
	public String[] getDiasdaSemana() {
		return diasdaSemana;
	}

	public void setDiasdaSemana(String[] diasdaSemana) {
		this.diasdaSemana = diasdaSemana;
	}

	@DynamoDBAttribute
	public String getDescricaoLocal() {
		return descricaoLocal;
	}

	public void setDescricaoLocal(String descricaoLocal) {
		this.descricaoLocal = descricaoLocal;
	}

	@DynamoDBAttribute
	public String getPortaria() {
		return portaria;
	}

	public void setPortaria(String portaria) {
		this.portaria = portaria;
	}

	@DynamoDBAttribute
	public String[] getRecursosVigilancia() {
		return recursosVigilancia;
	}

	public void setRecursosVigilancia(String[] recursosVigilancia) {
		this.recursosVigilancia = recursosVigilancia;
	}

	@DynamoDBAttribute
	public String getCep() {
		return cep;
	}

	public void setCep(String cep) {
		this.cep = cep;
	}

	@DynamoDBAttribute
	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@DynamoDBAttribute
	public String getCidade() {
		return cidade;
	}

	public void setCidade(String cidade) {
		this.cidade = cidade;
	}

	@DynamoDBAttribute
	public String getRua() {
		return rua;
	}

	public void setRua(String rua) {
		this.rua = rua;
	}

	@DynamoDBAttribute
	public String getBairro() {
		return bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	@DynamoDBAttribute
	public String getNumero() {
		return numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@DynamoDBAttribute
	public String getComplementoLocal() {
		return complementoLocal;
	}

	public void setComplementoLocal(String complementoLocal) {
		this.complementoLocal = complementoLocal;
	}

	@DynamoDBAttribute
	public String getTipoPagamento() {
		return tipoPagamento;
	}

	public void setTipoPagamento(String tipoPagamento) {
		this.tipoPagamento = tipoPagamento;
	}

	@DynamoDBAttribute
	public BigDecimal getPreco() {
		return preco;
	}

	public void setPreco(BigDecimal preco) {
		this.preco = preco;
	}

	@DynamoDBAttribute
	public String getTemIPTU() {
		return temIPTU;
	}

	public void setTemIPTU(String temIPTU) {
		this.temIPTU = temIPTU;
	}

	@DynamoDBAttribute
	public String[] getCanaisPagamento() {
		return canaisPagamento;
	}

	public void setCanaisPagamento(String[] canaisPagamento) {
		this.canaisPagamento = canaisPagamento;
	}

	@Override
	public String toString() {
		return "AluguelGaragem [id=" + id + ", nomeResponsavel=" + nomeResponsavel + ", codigoCadastro="
				+ codigoCadastro + ", emailResponsavel=" + emailResponsavel + ", contatoCelular=" + contatoCelular
				+ ", telefoneFixo=" + telefoneFixo + ", nomeBanco=" + nomeBanco + ", codigoBanco=" + codigoBanco
				+ ", numeroAgencia=" + numeroAgencia + ", contaCorrente=" + contaCorrente + ", chavePix=" + chavePix
				+ ", tituloAnuncio=" + tituloAnuncio + ", tipoLogradouroString=" + tipoLogradouroString
				+ ", tamanhoLocal=" + tamanhoLocal + ", tipoVeiculo=" + tipoVeiculo + ", capacidade=" + capacidade
				+ ", horarioFuncionamento=" + horarioFuncionamento + ", diasdaSemana=" + Arrays.toString(diasdaSemana)
				+ ", descricaoLocal=" + descricaoLocal + ", portaria=" + portaria + ", recursosVigilancia="
				+ Arrays.toString(recursosVigilancia) + ", cep=" + cep + ", estado=" + estado + ", cidade=" + cidade
				+ ", rua=" + rua + ", bairro=" + bairro + ", numero=" + numero + ", complementoLocal="
				+ complementoLocal + ", tipoPagamento=" + tipoPagamento + ", preco=" + preco + ", temIPTU=" + temIPTU
				+ ", canaisPagamento=" + Arrays.toString(canaisPagamento) + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + Arrays.hashCode(canaisPagamento);
		result = prime * result + Arrays.hashCode(diasdaSemana);
		result = prime * result + Arrays.hashCode(recursosVigilancia);
		result = prime * result + Objects.hash(bairro, capacidade, cep, chavePix, cidade, codigoBanco, codigoCadastro,
				complementoLocal, contaCorrente, contatoCelular, descricaoLocal, emailResponsavel, estado,
				horarioFuncionamento, id, nomeBanco, nomeResponsavel, numero, numeroAgencia, portaria, preco, rua,
				tamanhoLocal, telefoneFixo, temIPTU, tipoLogradouroString, tipoPagamento, tipoVeiculo, tituloAnuncio);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		AluguelGaragem other = (AluguelGaragem) obj;
		return Objects.equals(bairro, other.bairro) && Arrays.equals(canaisPagamento, other.canaisPagamento)
				&& Objects.equals(capacidade, other.capacidade) && Objects.equals(cep, other.cep)
				&& Objects.equals(chavePix, other.chavePix) && Objects.equals(cidade, other.cidade)
				&& Objects.equals(codigoBanco, other.codigoBanco)
				&& Objects.equals(codigoCadastro, other.codigoCadastro)
				&& Objects.equals(complementoLocal, other.complementoLocal)
				&& Objects.equals(contaCorrente, other.contaCorrente)
				&& Objects.equals(contatoCelular, other.contatoCelular)
				&& Objects.equals(descricaoLocal, other.descricaoLocal)
				&& Arrays.equals(diasdaSemana, other.diasdaSemana)
				&& Objects.equals(emailResponsavel, other.emailResponsavel) && Objects.equals(estado, other.estado)
				&& Objects.equals(horarioFuncionamento, other.horarioFuncionamento) && Objects.equals(id, other.id)
				&& Objects.equals(nomeBanco, other.nomeBanco) && Objects.equals(nomeResponsavel, other.nomeResponsavel)
				&& Objects.equals(numero, other.numero) && Objects.equals(numeroAgencia, other.numeroAgencia)
				&& Objects.equals(portaria, other.portaria) && Objects.equals(preco, other.preco)
				&& Arrays.equals(recursosVigilancia, other.recursosVigilancia) && Objects.equals(rua, other.rua)
				&& Objects.equals(tamanhoLocal, other.tamanhoLocal) && Objects.equals(telefoneFixo, other.telefoneFixo)
				&& Objects.equals(temIPTU, other.temIPTU)
				&& Objects.equals(tipoLogradouroString, other.tipoLogradouroString)
				&& Objects.equals(tipoPagamento, other.tipoPagamento) && Objects.equals(tipoVeiculo, other.tipoVeiculo)
				&& Objects.equals(tituloAnuncio, other.tituloAnuncio);
	}
}
